git show master:clustering.c > clustering.c
git show master:cvlr-cluster.c > cvlr-cluster.c
git show master:cvlr-meth-of-bam.c > cvlr-meth-of-bam.c
git show master:cvlrlib.c > cvlrlib.c
git show master:tree.c > tree.c
git show master:binomlib.ml > binomlib.ml
git show master:cvlr-stats.ml > cvlr-stats.ml
git show master:cvlr-stats.py > cvlr-stats.py
git show master:README.md > README.md
